#!/bin/bash
#
osch=0
echo "1. Unix (Sun Os)"
echo "2. Linux (Red Hat)"
echo -n "Vali enda operatsioonisüsteem [1 või 2]? "
read osch
if [ $osch -eq 1 ] ; then
     echo "Sa valisid (Sun Os) operatsioonisüsteemi"
else #### nested if i.e. if within if ######
       if [ $osch -eq 2 ] ; then
             echo "Sa valisid (Red Hat) operatsioonisüsteemi"
       else
             echo "Kas sulle ei meeldi Unix/Linux OS."
       fi
fi
#

