#!/bin/bash
#
# täisnurkse kolmnurga arvutamine
#
echo
echo -n "sisesta a kylje vaartus: "
read a
echo -n "sisesta b kylje vaartus: "
read b
aruut=`echo "scale=2;($a^2)" | bc` #arvutab a kylje ruudu
bruut=`echo "scale=2;($b^2)" | bc` #arvutab b kylje ruudu
summa=`echo "scale=2;($aruut+$bruut)" | bc` #arvutab a ja b kylje summa
c=`echo "scale=2;sqrt ($summa)" | bc` #vastus
echo c= $c #väljastab vastuse
#
# skript lõppes
