#!/bin/bash
#
# kasutaja tervitus
#
# skripti algus
#
# echo "Tere User!"
echo -n "Tere "
echo -n `whoami | cut -c1 | tr [:lower:] [:upper:]` #
echo -n `whoami | cut -c2-` #
echo "!"
#
# skripti lõpp
